server:
  port: 9696
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/UchihaArk/SpringCloudConfig
          search-paths: /
          username: 1812672160@qq.com
          password: wyh19960810
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
